name: Cypress E2E - Inmetrics

on:
  push:
    branches: [ci/setup]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configuração do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Instala dependências
        run: npm ci

      - name: Executa os testes com Cypress (modo headless)
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: 'cypress/e2e/**/*.feature'
          working-directory: ./
